# Generated by Django 4.2.11 on 2024-05-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('IT', 'IT'), ('mOBILE_Phones', 'Mobile 1')], max_length=50)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('activ', models.BooleanField(default=True)),
            ],
        ),
    ]
